[build]
  base = "/"
  publish = "dist"
  functions = "netlify-functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/netlify-functions/api.py"
  status = 200
